In [16]:
import pandas as pd

In [30]:
os.chdir('C:\\Users\\Zain Ahmed\\Desktop\\Literature review\\MetroData')

In [34]:
csvs = os.listdir()
csvs

['en_climate_hourly_NL_8403505_01-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_01-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_01-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_01-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_01-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_01-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_01-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_02-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_02-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_02-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_02-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_02-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_02-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_02-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_03-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_03-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_03-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_03-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_03-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_03-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_03-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_04-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_04-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_04-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_04-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_04-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_04-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_04-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_05-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_05-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_05-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_05-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_05-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_05-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_05-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_06-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_06-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_06-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_06-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_06-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_06-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_06-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_07-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_07-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_07-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_07-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_07-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_07-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_07-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_08-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_08-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_08-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_08-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_08-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_08-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_08-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_09-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_09-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_09-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_09-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_09-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_09-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_09-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_10-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_10-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_10-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_10-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_10-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_10-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_10-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_11-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_11-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_11-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_11-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_11-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_11-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_11-2022_P1H.csv',
 'en_climate_hourly_NL_8403505_12-2016_P1H.csv',
 'en_climate_hourly_NL_8403505_12-2017_P1H.csv',
 'en_climate_hourly_NL_8403505_12-2018_P1H.csv',
 'en_climate_hourly_NL_8403505_12-2019_P1H.csv',
 'en_climate_hourly_NL_8403505_12-2020_P1H.csv',
 'en_climate_hourly_NL_8403505_12-2021_P1H.csv',
 'en_climate_hourly_NL_8403505_12-2022_P1H.csv']

In [35]:
combined_csv = pd.concat([pd.read_csv(f) for f in csvs])

In [44]:
combined_csv

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time (LST),Year,Month,Day,Time (LST),Temp (Â°C),...,Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather
0,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 00:30,2016,1,1,00:30,-2.2,...,NaN,4.8,NaN,98.71,NaN,NaN,NaN,-7.0,NaN,Snow
1,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 01:30,2016,1,1,01:30,-2.2,...,NaN,3.2,NaN,98.55,NaN,NaN,NaN,-8.0,NaN,Snow
2,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 02:30,2016,1,1,02:30,-1.9,...,NaN,2.0,NaN,98.42,NaN,NaN,NaN,-7.0,NaN,Snow
3,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 03:30,2016,1,1,03:30,-1.5,...,NaN,2.4,NaN,98.26,NaN,NaN,NaN,-6.0,NaN,Snow
4,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 04:30,2016,1,1,04:30,-1.4,...,NaN,3.2,NaN,98.06,NaN,NaN,NaN,-6.0,NaN,Snow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 19:30,2022,12,31,19:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
740,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 20:30,2022,12,31,20:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
741,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 21:30,2022,12,31,21:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
742,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 22:30,2022,12,31,22:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
743,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 23:30,2022,12,31,23:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
os.chdir('C:\\Users\\Zain Ahmed\\Desktop\\Literature review\\Project Folder')

In [48]:
combined_csv['datetime'] = pd.to_datetime(combined_csv['Date/Time (LST)'],format='%Y-%m-%d %H:%M')

In [51]:
combined_csv = combined_csv.set_index('datetime')

In [53]:
combined_csv

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time (LST),Year,Month,Day,Time (LST),Temp (Â°C),...,Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather
datetime,,,,,,,,,,,,,,,,,,,,,
2016-01-01 00:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 00:30,2016,1,1,00:30,-2.2,...,NaN,4.8,NaN,98.71,NaN,NaN,NaN,-7.0,NaN,Snow
2016-01-01 01:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 01:30,2016,1,1,01:30,-2.2,...,NaN,3.2,NaN,98.55,NaN,NaN,NaN,-8.0,NaN,Snow
2016-01-01 02:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 02:30,2016,1,1,02:30,-1.9,...,NaN,2.0,NaN,98.42,NaN,NaN,NaN,-7.0,NaN,Snow
2016-01-01 03:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 03:30,2016,1,1,03:30,-1.5,...,NaN,2.4,NaN,98.26,NaN,NaN,NaN,-6.0,NaN,Snow
2016-01-01 04:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2016-01-01 04:30,2016,1,1,04:30,-1.4,...,NaN,3.2,NaN,98.06,NaN,NaN,NaN,-6.0,NaN,Snow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 19:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 19:30,2022,12,31,19:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-31 20:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 20:30,2022,12,31,20:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-31 21:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 21:30,2022,12,31,21:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-31 22:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 22:30,2022,12,31,22:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-31 23:30:00,-52.75,47.62,ST. JOHN'S INTL A,8403505,2022-12-31 23:30,2022,12,31,23:30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
combined_csv.to_csv('metro_data.csv')